name: PdM-Evaluation
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - absl-py==2.1.0
      - alembic==1.12.0
      - arch==5.3.1
      - arm-mango==1.4.0
      - asttokens==2.4.0
      - astunparse==1.6.3
      - attrdict==2.0.1
      - backcall==0.2.0
      - blinker==1.6.3
      - cachetools==5.3.3
      - certifi==2023.7.22
      - charset-normalizer==3.3.1
      - click==8.1.7
      - cloudpickle==2.2.1
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.36
      - databricks-cli==0.18.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - docker==6.1.3
      - dtaidistance==2.3.11
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - filelock==3.13.1
      - flask==2.3.3
      - flatbuffers==24.3.25
      - fonttools==4.43.1
      - fsspec==2023.12.2
      - future==0.18.3
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.0
      - grpcio==1.63.0
      - gunicorn==21.2.0
      - h5py==3.11.0
      - hurst==0.0.5
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - iniconfig==2.0.0
      - ipykernel==6.26.0
      - ipython==8.16.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.18.6
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.5
      - lightgbm==3.3.5
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - more-itertools==10.1.0
      - nbclient==0.9.1
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - numpy==1.25.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.1.1
      - parso==0.8.3
      - patsy==0.5.6
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - platformdirs==3.11.0
      - pluggy==1.3.0
      - prompt-toolkit==3.0.39
      - property-cached==1.6.4
      - protobuf==4.24.4
      - prts==1.0.0.3
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.16.1
      - pyjwt==2.8.0
      - pyparsing
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - querystring-parser==1.2.4
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - six==1.16.0
      - smmap==5.0.1
      - sqlalchemy==2.0.22
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - statsmodels==0.13.2
      - stumpy==1.8.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.29.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tomli==2.0.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - tsfresh==0.8.1
      - tslearn==0.6.3
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - wcwidth==0.2.8
      - websocket-client==1.6.4
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - zipp==3.17.0
      - locket
      - mypy-extensions